### ISSUE TITLE
Juju Bootstrap LXD LXD fails on non default bridge ?

### ISSUE THREAD

**Issue by devekko** [juju/juju#4652] opened 2016-03-08 09:01 UTC
I seem to be stuck in a catch-22/bootstrapping problem

I have LXD/LXC configured to use a br0 host bridge but when I try to create juju bootstrap lxd lxd it fails giving warmings about lxcbr0

I know there is config in the enviroments.yaml (or whatever that file is now called) but I cant find the equivalent command to juju generate-config show

**Comment by cherylj** [comment] 2016-03-08 17:55
The bridge device isn't configurable through juju, but should be picked up if set in your default lxd profile (can edit through 'lxc profile edit default').  Let me know if that works for you.

**Comment by devekko** [comment] 2016-03-08 21:27
hi, no joy


lxc profile edit default

name: default
config: {}
description: LXD arizmendix
devices:
  enpghfddh0:
    nictype: bridged
    parent: br0
    type: nic


lxc list
+--------------------+---------+--------------------------------+---------------------------------------------+------------+-----------+
|        NAME        |  STATE  |              IPV4              |                    IPV6                     |    TYPE    | SNAPSHOTS |
+--------------------+---------+--------------------------------+---------------------------------------------+------------+-----------+
| centos             | STOPPED |                                |                                             | PERSISTENT | 0         |
+--------------------+---------+--------------------------------+---------------------------------------------+------------+-----------+
| debops             | STOPPED |                                |                                             | PERSISTENT | 0         |
+--------------------+---------+--------------------------------+---------------------------------------------+------------+-----------+
| devshop            | STOPPED |                                |                                             | PERSISTENT | 0         |
+--------------------+---------+--------------------------------+---------------------------------------------+------------+-----------+
| REDACTED | RUNNING | REDACTED (eth0)           | REDACTED (eth0) | PERSISTENT | 0         |
|                    |         | 10.1.10.133 (eth0)             |                                             |            |           |
+--------------------+---------+--------------------------------+---------------------------------------------+------------+-----------+
| my-docker-host     | STOPPED |                                |                                             | PERSISTENT | 0         |
+--------------------+---------+--------------------------------+---------------------------------------------+------------+-----------+
| my-ubuntu          | STOPPED |                                |                                             | PERSISTENT | 0         |
+--------------------+---------+--------------------------------+---------------------------------------------+------------+-----------+
| my-ubuntu-dev      | STOPPED |                                |                                             | PERSISTENT | 0         |
+--------------------+---------+--------------------------------+---------------------------------------------+------------+-----------+
| transportive-queen | STOPPED |                                |                                             | PERSISTENT | 0         |
+--------------------+---------+--------------------------------+---------------------------------------------+------------+-----------+
| turdine-skye       | STOPPED |                                |                                             | PERSISTENT | 0         |
+--------------------+---------+--------------------------------+---------------------------------------------+------------+-----------+

**Comment by devekko** [comment] 2016-03-09 02:22
ok, I think its https://bugs.launchpad.net/juju-core/+bug/1547268/comments/14

will try again later in the week

I did also get into a huge mess with 2 different juju versions running

I assume there will be a pretty major edit on the docs when xenial drops

**Comment by devekko** [comment] 2016-03-09 02:27
actually, more correctly, I assume this issue is actually related to the launchpad one above

although, they may be separate and unrelated

but, when I switched to lxcbr0 I got a similar message https://bugs.launchpad.net/juju-core/+bug/1547268/comments/14

which makes me think, my non standard bridge error is based on the error in launchpad

**Comment by cherylj** [comment] 2016-03-09 02:55
Yeah, we are doing major updates to docs and help text for 2.0 / xenial.

**Comment by devekko** [comment] 2016-03-09 04:00
thanks, excuse my grumps, I did a couple of 10 hour stints working through juju / lxd for the first time ... 

exciting projects !

**Comment by devekko** [comment] 2016-03-13 02:25
hmm

I updated and still get same error

devekko@arizmendix:~$ juju --version
2.0-beta2-xenial-amd64
devekko@arizmendix:~$ juju bootstrap lxd lxd
ERROR cannot find network interface "lxcbr0": route ip+net: no such network interface
ERROR invalid config: route ip+net: no such network interface

**Comment by devekko** [comment] 2016-03-13 03:50
and I have been having no problems with Juju 1.25 and the local provider there

can spin up Wordpress or Mediawiki and make them public IP from my local machine

**Comment by Kriechi** [comment] 2016-04-20 09:44
I have the same problem.
I managed to start lxd manually (`systemctl start lxd`), but now I'm getting: `ERROR invalid config: no addresses match`. The bridge interface is there in ifconfig, but it has no IP or anything...

**Comment by bz2** [comment] 2016-04-20 15:20
@Kriechi you probably just need to reconfigure the bridge again, do:

```
$ sudo dpkg-reconfigure -p medium lxd
$ lxd finger
```

See https://bugs.launchpad.net/juju-core/+bug/1571593 for more.

**Comment by niccolox** [comment] 2016-05-21 02:53
tried above and still have errors https://github.com/juju/juju/issues/5439

**Comment by dimitern** [comment] 2016-08-02 12:11
Closing as a fix for the root cause will soon land as #5871

**Closed by dimitern** 2016-08-02 12:11 UTC

**Comment by niccolox** [comment] 2016-08-04 15:20
this isn't fixed for me

I upgraded

this fails

```
juju bootstrap lxd-tests3 lxd  
ERROR cannot find network interface "lxdbr0": route ip+net: no such network interface
ERROR invalid config: route ip+net: no such network interface
```


this seems to work

```
devekko@arizmendix ~ $ juju bootstrap --upload-tools man manual/10.1.10.61
Creating Juju controller "man" on manual
Bootstrapping model "controller"
Starting new instance for initial controller
Building tools to upload (2.0-beta13.1-xenial-amd64)
Installing Juju agent on bootstrap instance
Preparing for Juju GUI 2.1.8 release installation
sudo: unable to resolve host man-x1
Logging to /var/log/cloud-init-output.log on remote host
Running apt-get update
Installing package: curl
Installing package: cpu-checker
Installing package: bridge-utils
Installing package: cloud-utils
Installing package: cloud-image-utils
Installing package: tmux
Bootstrapping Juju machine agent
Starting Juju machine agent (jujud-machine-0)
Bootstrap agent installed
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Waiting for API to become available: upgrade in progress (upgrade in progress)
Bootstrap complete, man now available.

```

**Comment by niccolox** [comment] 2016-08-04 15:40
ok, my mistake, I need to either compile juju or wait for the deb to be updated to beta14

https://github.com/juju/juju/commit/df65efda1f36866589e52415d5464915709aa511
