### ISSUE TITLE
juju can't bootstrap at Azure

### ISSUE THREAD

**Issue by fenris** [juju/juju#3313] opened 2015-09-17 19:56 UTC
2015-09-17 19:49:21 INFO juju.cmd cmd.go:114 Starting new instance for initial state server
Launching instance
2015-09-17 19:50:04 DEBUG juju.cloudconfig.instancecfg instancecfg.go:520 Setting numa ctl preference to false
2015-09-17 19:50:04 INFO juju.provider.azure environ.go:724 picked tools &{"1.25-alpha1-trusty-amd64" "https://jujutools.blob.core.windows.net/juju-tools/tools/devel/juju-1.25-alph
2015-09-17 19:50:04 DEBUG juju.service discovery.go:65 discovered init system "upstart" from series "trusty"
2015-09-17 19:50:04 DEBUG juju.provider.azure customdata.go:21 user data; 683 bytes
2015-09-17 19:50:04 DEBUG juju.provider.azure customdata.go:23 base64-encoded custom data: 912 bytes
2015-09-17 19:50:04 DEBUG juju.environs imagemetadata.go:112 using image datasource "default cloud images"
2015-09-17 19:50:06 DEBUG juju.environs.simplestreams simplestreams.go:429 read metadata index at "http://cloud-images.ubuntu.com/releases/streams/v1/index.sjson"
2015-09-17 19:50:07 DEBUG juju.environs.simplestreams simplestreams.go:968 metadata: &{map[com.ubuntu.cloud:server:12.04:amd64:{precise 12.04 amd64   map[20140806:0x17280ae0 201509
0325:0x1725a420 20150512:0x1716dbd0 20150522.1:0x16ffac60 20140514:0x172802a0 20140927:0x17280ea0 20140127:0x1725a000 20150728:0x1714cae0 20121218:0x17257450 20140408:0x17257870 20
20140925.1:0x1716d810 20150707:0x1714c480 20130827:0x1736c0f0 20130916.1:0x1736c450 20130225:0x17268cc0 20140925.2:0x16fb72a0 20150610:0x16fe00c0 20131114:0x16fe0480 20130603:0x16f
x16fb7660 20130624:0x16fb7e10 20131111:0x16fe0fc0 20140227:0x16ffa5d0 20140923.1:0x16ffa8d0 20130909:0x170437b0 20140606:0x1716d0c0 20140924.4:0x17280600 20150127:0x1725aae0 201407
14.04 amd64   map[20140618.1:0x17015fc0 20150706:0x17015ab0 20140909:0x17023450 20140416.1:0x1703c030 beta1:0x1703c960 20150805:0x1703cdb0 20140927:0x170473c0 20140528:0x17015600 2
a0 20140414:0x17015ea0 20150123:0x1703c4e0 20140724:0x1703ca80 20140926:0x17047060]} com.ubuntu.cloud:server:15.10:amd64:{wily 15.10 amd64   map[alpha2:0x17047b10 alpha1:0x17047f30
 20150421:0x16fa9570 20150611:0x17053960 20150616.1:0x17053c90 beta2:0x16fb2c90 20150420.1:0x16fc65a0 20150818:0x16fc6e40 beta1:0x16fa9180 20150728:0x16fa9e10 20150417.1:0x172dd210
f37ed0]} com.ubuntu.cloud:server:14.10:amd64:{utopic 14.10 amd64   map[beta1:0x172dd570]}] map[crsn:map[East US 2:map[region:East US 2 endpoint:https://management.core.windows.net/
point:https://management.core.windows.net/] North Europe:map[region:North Europe endpoint:https://management.core.windows.net/] Japan East:map[region:Japan East endpoint:https://ma
a Southeast:map[region:Australia Southeast endpoint:https://management.core.windows.net/] West India:map[region:West India endpoint:https://management.core.windows.net/] North Cent
int:https://management.core.chinacloudapi.cn/] South India:map[region:South India endpoint:https://management.core.windows.net/] China North:map[region:China North endpoint:https:/
 Europe:map[region:West Europe endpoint:https://management.core.windows.net/] East Asia:map[region:East Asia endpoint:https://management.core.windows.net/] East US:map[region:East
ows.net/] Southeast Asia:map[region:Southeast Asia endpoint:https://management.core.windows.net/] Central India:map[region:Central India endpoint:https://management.core.windows.ne
:50 +0000 products:1.0 com.ubuntu.cloud:released:azure  }
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:154 role size "Basic_A0" is unsupported
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:154 role size "Basic_A1" is unsupported
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:154 role size "Basic_A2" is unsupported
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:154 role size "Basic_A3" is unsupported
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:154 role size "Basic_A4" is unsupported
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:147 role size "A8" is unavailable in location "East Asia"
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:147 role size "A9" is unavailable in location "East Asia"
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:147 role size "Standard_G1" is unavailable in location "East Asia"
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:147 role size "Standard_G2" is unavailable in location "East Asia"
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:147 role size "Standard_G3" is unavailable in location "East Asia"
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:147 role size "Standard_G4" is unavailable in location "East Asia"
2015-09-17 19:50:07 DEBUG juju.provider.azure instancetype.go:147 role size "Standard_G5" is unavailable in location "East Asia"
2015-09-17 19:50:07 INFO juju.environs.instances image.go:90 find instance - using image with id: b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_3-LTS-amd64-server-20150805-en-us-3
2015-09-17 19:50:07 DEBUG juju.provider.azure environ.go:641 creating instance in new cloud service
2015-09-17 19:51:41 DEBUG juju.cmd.juju common.go:103 Destroying environment.
2015-09-17 19:51:41 INFO juju.cmd cmd.go:114 Bootstrap failed, destroying environment
2015-09-17 19:51:41 DEBUG juju.provider.azure environ.go:1152 destroying environment "azure"
2015-09-17 19:51:56 ERROR juju.cmd supercommand.go:429 failed to bootstrap environment: cannot start bootstrap instance: error creating VM deployment: asynchronous operation failed
ror)

c:\>juju status --debug
2015-09-17 19:54:02 INFO juju.cmd supercommand.go:37 running juju [1.25-alpha1-win10-i386 gc]
2015-09-17 19:54:02 DEBUG juju.api api.go:162 no cached API connection settings found
2015-09-17 19:54:02 DEBUG juju.provider.azure environprovider.go:25 opening environment "azure".
2015-09-17 19:54:05 ERROR juju.cmd supercommand.go:429 Unable to connect to environment "azure".
Please check your credentials or use 'juju bootstrap' to create a new environment.

Error details:
instances not found

**Comment by fenris** [comment] 2015-09-17 20:20
putting the constraints make it enable to bootstrap.. 

juju bootstrap --constraints "instance-type=<instance type>"

valid values are: [ExtraSmall Small Medium Large ExtraLarge A5 A6 A7 Standard_D1 Standard_D2 Standard_D3 Standard_D4 Standard_D11 Standard_D12 Standard_D13 Standard_D14]

is it documented juju with Azure documentation ? or is it by default can bootstrap without set the constraints?

**Comment by fenris** [comment] 2015-09-17 20:27
c:\>juju deploy juju-gui --to 0 --debug
2015-09-17 20:25:54 INFO juju.cmd supercommand.go:37 running juju [1.25-alpha1-win10-i386 gc]
2015-09-17 20:25:54 DEBUG juju.api api.go:154 trying cached API connection settings - endpoints [168.63.141.192:17070 10.0.0.4:17070]
2015-09-17 20:25:54 INFO juju.api api.go:266 connecting to API addresses: [168.63.141.192:17070 10.0.0.4:17070]
2015-09-17 20:25:54 INFO juju.api apiclient.go:262 dialing "wss://168.63.141.192:17070/environment/83cbfc56-13c0-4436-8e92-ab52316298e0/api"
2015-09-17 20:25:54 INFO juju.api apiclient.go:262 dialing "wss://10.0.0.4:17070/environment/83cbfc56-13c0-4436-8e92-ab52316298e0/api"
2015-09-17 20:25:54 INFO juju.api apiclient.go:194 connection established to "wss://168.63.141.192:17070/environment/83cbfc56-13c0-4436-8e92-ab52316298e0/api"
2015-09-17 20:25:55 DEBUG juju.api api.go:466 API hostnames changed from [juju-azure-whtjoptqk7.cloudapp.net:17070 10.0.0.4:17070] to [168.63.141.192:17070 juju-azure-whtjoptqk7.cloudapp.net:17070 10.0.0.4:17070] - resolving hostnames
2015-09-17 20:25:55 DEBUG juju.api api.go:497 API addresses unchanged
2015-09-17 20:25:55 DEBUG juju.api api.go:506 cacheChangedAPIInfo: serverUUID="83cbfc56-13c0-4436-8e92-ab52316298e0"
2015-09-17 20:25:55 DEBUG httpbakery client.go:224 client do GET https://api.jujucharms.com/charmstore/v4/juju-gui/meta/any?include=id {
2015-09-17 20:25:57 DEBUG httpbakery client.go:226 } -> error <nil>
2015-09-17 20:26:10 INFO juju.cmd cmd.go:114 Added charm "cs:trusty/juju-gui-38" to the environment.
2015-09-17 20:26:15 DEBUG juju.api apiclient.go:268 error dialing "wss://10.0.0.4:17070/environment/83cbfc56-13c0-4436-8e92-ab52316298e0/api", will retry: websocket.Dial wss://10.0.0.4:17070/environment/83cbfc56-13c0-4436-8e92-ab52316298e0/api: dial tcp 10.0.0.4:17070: ConnectEx tcp: A connection at
tempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2015-09-17 20:26:23 ERROR juju.cmd supercommand.go:429 cannot assign unit "juju-gui/0" to machine 0: unit placement is not supported with availability-sets-enabled

**Comment by fenris** [comment] 2015-09-17 20:30
error above can't assigned unit "juju-gui/0" but when checking status : 

C:\Users\KhairulAizat>juju status
environment: azure
machines:
  "0":
    agent-state: started
    agent-version: 1.25-alpha1
    dns-name: juju-azure-whtjoptqk7.cloudapp.net
    instance-id: juju-azure-whtjoptqk7-jujuspno7zn4r9z4i7l191c06vtdkjupww5gxy8c76s4377h41
    instance-state: ReadyRole
    series: trusty
    hardware: arch=amd64 cpu-cores=2 mem=3584M root-disk=130048M
    state-server-member-status: has-vote
services:
  juju-gui:
    charm: cs:trusty/juju-gui-38
    exposed: false
    service-status:
      current: unknown
      message: Waiting for agent initialization to finish
      since: 18 Sep 2015 04:26:15+08:00
    units:
      juju-gui/0:
        workload-status:
          current: unknown
          message: Waiting for agent initialization to finish
          since: 18 Sep 2015 04:26:15+08:00
        agent-status:
          current: allocating
          since: 18 Sep 2015 04:26:15+08:00
        agent-state: pending

**Comment by axw** [comment] 2015-10-22 02:25
@fenris Sorry for taking so long to respond. Bugs for Juju are typically handled over on launchpad (https://launchpad.net/juju-core), and I haven't been keeping an eye on this.

I've just managed to bootstrap on Azure in the "East Asia" location without any problems. I did not need to specify constraints. I'm guessing it was a transient failure, but I'm not really sure.

As to the issue of juju-gui, it looks like we're not rejecting the placement early enough. The unit will stay "pending" forever in that case. FYI, Microsoft have recently introduced an improved API/model for Azure which we're working on integrating into Juju. When that work is done, you should be able to use placement ("--to") without issue.

If you're still having problems, please let us know.

**Comment by mattyw** [comment] 2015-11-18 13:16
@fenris @axw can we close this issue?

**Comment by axw** [comment] 2015-11-18 23:36
I think so. @frenris, please let us know if you're still experiencing issues. The new Azure provider is coming out very soon, so please give it a shot if you're interested and let us know how it goes.

**Comment by fenris** [comment] 2015-11-19 04:37
sure can close this issue as I give another spin on azure as below: 

PS C:\Users\KhairulAizat> juju --version
1.26-alpha1-win10-i386
PS C:\Users\KhairulAizat> juju bootstrap
Bootstrapping environment "azure"
Starting new instance for initial state server
Launching instance
 - juju-azure-m730yzeal7-juju07bu3s3y55d4q65x4unwq3q4sxm3xbuov84eum8m6mgixu
Installing Juju agent on bootstrap instance
Waiting for address
Attempting to connect to 10.0.0.4:22
Attempting to connect to juju-azure-m730yzeal7.cloudapp.net:22
Logging to /var/log/cloud-init-output.log on remote host
Running apt-get update
Running apt-get upgrade
Installing package: curl
Installing package: cpu-checker
Installing package: bridge-utils
Installing package: rsyslog-gnutls
Installing package: cloud-utils
Installing package: cloud-image-utils
Installing package: tmux
Fetching tools: curl -sSfw 'tools from %{url_effective} downloaded: HTTP %{http_code}; time %{time_total}s; size %{size_
download} bytes; speed %{speed_download} bytes/s ' --retry 10 -o $bin/tools.tar.gz <[https://jujutools.blob.core.windows
.net/juju-tools/tools/devel/juju-1.26-alpha1-trusty-amd64.tgz]>
Bootstrapping Juju machine agent
Starting Juju machine agent (jujud-machine-0)
Bootstrap agent installed
Bootstrap complete
PS C:\Users\KhairulAizat>
PS C:\Users\KhairulAizat> juju status
environment: azure
machines:
  "0":
    agent-state: started
    agent-version: 1.26-alpha1
    dns-name: juju-azure-m730yzeal7.cloudapp.net
    instance-id: juju-azure-m730yzeal7-juju07bu3s3y55d4q65x4unwq3q4sxm3xbuov84eum8m6mgixu
    instance-state: ReadyRole
    series: trusty
    hardware: arch=amd64 cpu-cores=1 mem=1792M root-disk=130048M
    state-server-member-status: has-vote
services: {}
PS C:\Users\KhairulAizat>

sure, I would interested to give a shot with another new azure provider (other than Microsoft?)

**Comment by axw** [comment] 2015-11-19 05:11
@fenris Great, glad it's working now.

> sure, I would interested to give a shot with another new azure provider (other than Microsoft?)

It's still Microsoft Azure, it's just using a different set of APIs. This has enabled us to implement a more featureful provider. It will enable unit placement (--to), persistent volumes, multi-environment, and Windows support. Look out for the 1.26-alpha2 announcement on the juju mailing list.

**Comment by fenris** [comment] 2015-12-01 08:03
fenris@macbuntu:~$ juju bootstrap
Bootstrapping environment "azure"
Starting new instance for initial state server
Launching instance
juju-azure-9pfl7hks2w-jujuyuebzo9kvtu649j4npmt18psrzkicqspbdgkah1zly0zxg
Installing Juju agent on bootstrap instance
Waiting for address
Attempting to connect to 10.0.0.4:22
Attempting to connect to juju-azure-9pfl7hks2w.cloudapp.net:22
Logging to /var/log/cloud-init-output.log on remote host
Running apt-get update
Running apt-get upgrade
Installing package: curl
Installing package: cpu-checker
Installing package: bridge-utils
Installing package: rsyslog-gnutls
Installing package: cloud-utils
Installing package: cloud-image-utils
Installing package: tmux
Fetching tools: curl -sSfw 'tools from %{url_effective} downloaded: HTTP %{http_code}; time %{time_total}s; size %{size_download} bytes; speed %{speed_download} bytes/s ' --retry 10 -o $bin/tools.tar.gz <[https://jujutools.blob.core.windows.net/juju-tools/tools/devel/juju-1.26-alpha2-trusty-amd64.tgz]>
Bootstrapping Juju machine agent
Starting Juju machine agent (jujud-machine-0)
Bootstrap agent installed
Bootstrap complete
fenris@macbuntu:~$ juju status --format=tabular
[Services] 
NAME       STATUS EXPOSED CHARM 

[Units] 
ID      STATE VERSION MACHINE PORTS PUBLIC-ADDRESS 

[Machines] 
ID         STATE   DNS                                INS-ID                                                                   SERIES AZ 
0          started juju-azure-9pfl7hks2w.cloudapp.net juju-azure-9pfl7hks2w-jujuyuebzo9kvtu649j4npmt18psrzkicqspbdgkah1zly0zxg trusty    

fenris@macbuntu:~$ juju deploy juju-gui --to 0
Added charm "cs:trusty/juju-gui-41" to the environment.
fenris@macbuntu:~$ juju status --format=tabular
[Services] 
NAME       STATUS EXPOSED CHARM                 
juju-gui   error  false   cs:trusty/juju-gui-41 

[Units]    
ID         WORKLOAD-STATE AGENT-STATE VERSION MACHINE PORTS PUBLIC-ADDRESS MESSAGE                                                                                                      
juju-gui/0 error          lost                                             cannot assign unit "juju-gui/0" to machine 0: unit placement is not supported with availability-sets-enabled 

[Machines] 
ID         STATE   DNS                                INS-ID                                                                   SERIES AZ 
0          started juju-azure-9pfl7hks2w.cloudapp.net juju-azure-9pfl7hks2w-jujuyuebzo9kvtu649j4npmt18psrzkicqspbdgkah1zly0zxg trusty

What does this error mean "lost cannot assign unit "juju-gui/0" to machine 0: unit placement is not supported with availability-sets-enabled"

**Comment by axw** [comment] 2015-12-01 08:19
It's actually just `cannot assign unit "juju-gui/0" to machine 0: unit placement is not supported with availability-sets-enabled`. The "lost" is from the previous column, and means that Juju hasn't seen the agent pinging back recently (that's a separate issue that is being worked on).

The "unit placement is nto supported ..." error is due to a limitation in the current Azure provider; you either use availability sets and get HA services (default), or you disable HA and enable placement. The new provider does not have this limitation.

**Comment by ppbrown** [comment] 2016-01-26 19:11
Hello. This was first google hit on the error about cannot place.
Would you please give specifics on HOW you do one of the other?
Since I like HA, I guess my preference would be how do I change the juju defaults for azure, to not use placement?

**Comment by axw** [comment] 2016-01-26 22:57
@ppbrown 
> Hello. This was first google hit on the error about cannot place.
> Would you please give specifics on HOW you do one of the other?
> Since I like HA, I guess my preference would be how do I change the juju defaults for azure, to not use placement?

The default for the Azure provider is to use availability sets, and disable the ability to place units on specific machines. You can override this by adding the following to your environments.yaml, in your azure environment's config:

    availability-sets-enabled: false

If you're just getting started with Juju and Azure, please be aware that the Azure provider that exists in Juju 1.25 and earlier will be replaced entirely in Juju 2.0, which is due around April. If you can tolerate running an alpha release, please give Juju 2.0-alpha1 a try.

**Comment by ppbrown** [comment] 2016-01-27 01:12
thanks for the reply, but... that was the exact opposite of what I asked for? :-}
i'd like to keep availability sets on, but disable specific placement.

(you say that is already the default, but, apparently it isnt, becuse I havent set placement anywhere, but the gui is still complaining about it)

**Comment by axw** [comment] 2016-01-27 01:35
> thanks for the reply, but... that was the exact opposite of what I asked for? :-}
> i'd like to keep availability sets on, but disable specific placement.

Availability sets are on by default, and placement is disabled by default (for Azure only). You can enable/disable by setting `availability-sets-enabled` to `true` or `false` in environments.yaml. I think this answers your question, please clarify if I'm still missing the point. It sounds like there might be an issue with something you're using in the GUI.

> (you say that is already the default, but, apparently it isnt, becuse I havent set placement anywhere, but the gui is still complaining about it)

If you're getting an error about placement, that's an indication that availability set support *is* enabled. Can you describe what you're doing in the GUI? Perhaps the GUI is using placement under the hood for whatever that is, and it's just not obvious.

**Comment by ppbrown** [comment] 2016-01-27 04:41
>
> I'm just using the defaults of the GUI.
>
select the charm, press commit, press deploy. nothing else

I do notice that there is a toggle between auto place vs don't place

the default is *autoplace*

if I change it to (not place)...
it never seems to actually deploy anything!

whereas if I leave it to autoplace...
it has the popup whine, but seems to eventually deploy it properly anyway.

**Comment by axw** [comment] 2016-01-27 05:52
@ppbrown Thanks, I can reproduce that. That looks like a GUI bug; I'll file a bug over there. When it's on "autoplace", it should behave just as if you did "juju deploy <service>" on the command-line, which works as expected.

**Closed** 2016-08-19 13:39 UTC
